### ISSUE TITLE
Create a initial handshake setup in the follower service

### ISSUE THREAD

**Issue by dhanushthakkalapally** [dhanushthakkalapally/dynamicContainerManager#17]
**Description:**
When ever the new container has been spawned up the follower process should communicate with dictator over broker; saying it is ready to receive messages, so point of this ticket is to setup that acknowledges meant process and setup the test environment to test the acknowledgement process

**Tasks:**

- [x] Setup test environment in the follower service so to emulate all the scenarios.
- [x] Design initial handshake setup between dictator and follower
- [x] implement the handshake scenario as well.
