### ISSUE TITLE
Setup postgres db and initial model in dictator

### ISSUE THREAD

**Issue by dhanushthakkalapally** [dhanushthakkalapally/dynamicContainerManager#9]
**Description:**
Now we need have table to store the information about the containers or followers we are creating in the system, and to expose to the users 

**Tasks:**

- [x] setup postgres database to store data
- [x] setup sequelize to connect to database and its tables
- [x] setup model definitions
